
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Category: 'Category',
  DailyLog: 'DailyLog',
  HourlyBlock: 'HourlyBlock',
  Goal: 'Goal',
  Challenge: 'Challenge',
  ChallengeDay: 'ChallengeDay',
  Reminder: 'Reminder',
  CheckIn: 'CheckIn',
  Experiment: 'Experiment'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  displayName: 'displayName',
  createdAt: 'createdAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  group: 'group',
  createdAt: 'createdAt'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const DailyLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  date: 'date',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DailyLogScalarFieldEnum = (typeof DailyLogScalarFieldEnum)[keyof typeof DailyLogScalarFieldEnum]


export const HourlyBlockScalarFieldEnum = {
  id: 'id',
  dailyLogId: 'dailyLogId',
  hourIndex: 'hourIndex',
  categoryId: 'categoryId',
  activity: 'activity',
  plannedTask: 'plannedTask',
  distraction: 'distraction',
  missedPlanReason: 'missedPlanReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type HourlyBlockScalarFieldEnum = (typeof HourlyBlockScalarFieldEnum)[keyof typeof HourlyBlockScalarFieldEnum]


export const GoalScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  targetValue: 'targetValue',
  dueDate: 'dueDate',
  progress: 'progress',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GoalScalarFieldEnum = (typeof GoalScalarFieldEnum)[keyof typeof GoalScalarFieldEnum]


export const ChallengeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  targetDays: 'targetDays',
  startDate: 'startDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ChallengeScalarFieldEnum = (typeof ChallengeScalarFieldEnum)[keyof typeof ChallengeScalarFieldEnum]


export const ChallengeDayScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  dayNumber: 'dayNumber',
  date: 'date',
  description: 'description',
  category: 'category',
  createdAt: 'createdAt'
} as const

export type ChallengeDayScalarFieldEnum = (typeof ChallengeDayScalarFieldEnum)[keyof typeof ChallengeDayScalarFieldEnum]


export const ReminderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  timeOfDay: 'timeOfDay',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReminderScalarFieldEnum = (typeof ReminderScalarFieldEnum)[keyof typeof ReminderScalarFieldEnum]


export const CheckInScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  date: 'date',
  period: 'period',
  energy: 'energy',
  focus: 'focus',
  mood: 'mood',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CheckInScalarFieldEnum = (typeof CheckInScalarFieldEnum)[keyof typeof CheckInScalarFieldEnum]


export const ExperimentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  description: 'description',
  startDate: 'startDate',
  endDate: 'endDate',
  metrics: 'metrics',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ExperimentScalarFieldEnum = (typeof ExperimentScalarFieldEnum)[keyof typeof ExperimentScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

