import { Router } from 'express'
import { z } from 'zod'
import { ChallengeCategory } from '../generated/prisma/client.js'
import { getLocalProfile } from '../lib/localProfile.js'
import { prisma } from '../lib/prisma.js'
const router = Router(); const categories = Object.values(ChallengeCategory) as [ChallengeCategory, ...ChallengeCategory[]]
const start = (date: Date) => new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()))
async function currentChallenge() { const user = await getLocalProfile(); return prisma.challenge.upsert({ where: { id: (await prisma.challenge.findFirst({ where: { userId: user.id }, orderBy: { startDate: 'desc' } }))?.id ?? 'missing' }, update: {}, create: { userId: user.id, startDate: start(new Date()) }, include: { days: { orderBy: { date: 'desc' } } } }) }
function view(challenge: Awaited<ReturnType<typeof currentChallenge>>) { const today = start(new Date()); const dayNumber = Math.min(challenge.targetDays, Math.floor((today.getTime() - challenge.startDate.getTime()) / 86400000) + 1); const distribution = categories.map(category => ({ category, count: challenge.days.filter(day => day.category === category).length })).filter(x => x.count); return { dayNumber, targetDays: challenge.targetDays, progress: Number(((dayNumber / challenge.targetDays) * 100).toFixed(0)), entries: challenge.days.map(day => ({ dayNumber: day.dayNumber, date: day.date.toISOString().slice(0, 10), description: day.description, category: day.category })), distribution: distribution.map(x => ({ ...x, percentage: challenge.days.length ? Number(((x.count / challenge.days.length) * 100).toFixed(0)) : 0 })) } }
router.get('/challenge', async (_q, res, next) => { try { res.json(view(await currentChallenge())) } catch (e) { next(e) } })
router.post('/challenge/today', async (req, res, next) => { try { const parsed = z.object({ description: z.string().trim().min(1).max(400), category: z.enum(categories) }).safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Add a description and category.' }); const challenge = await currentChallenge(); const today = start(new Date()); const dayNumber = Math.floor((today.getTime() - challenge.startDate.getTime()) / 86400000) + 1; if (dayNumber > challenge.targetDays) return res.status(400).json({ message: 'This challenge is complete.' }); await prisma.challengeDay.upsert({ where: { challengeId_date: { challengeId: challenge.id, date: today } }, update: parsed.data, create: { challengeId: challenge.id, dayNumber, date: today, ...parsed.data } }); res.json(view(await currentChallenge())) } catch (e) { next(e) } })
export default router
