
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ChallengeDay` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../backend/src/generated/prisma/enums.js"
import type * as Prisma from "../backend/src/generated/prisma/internal/prismaNamespace.js"

/**
 * Model ChallengeDay
 * 
 */
export type ChallengeDayModel = runtime.Types.Result.DefaultSelection<Prisma.$ChallengeDayPayload>

export type AggregateChallengeDay = {
  _count: ChallengeDayCountAggregateOutputType | null
  _avg: ChallengeDayAvgAggregateOutputType | null
  _sum: ChallengeDaySumAggregateOutputType | null
  _min: ChallengeDayMinAggregateOutputType | null
  _max: ChallengeDayMaxAggregateOutputType | null
}

export type ChallengeDayAvgAggregateOutputType = {
  dayNumber: number | null
}

export type ChallengeDaySumAggregateOutputType = {
  dayNumber: number | null
}

export type ChallengeDayMinAggregateOutputType = {
  id: string | null
  challengeId: string | null
  dayNumber: number | null
  date: Date | null
  description: string | null
  category: $Enums.ChallengeCategory | null
  createdAt: Date | null
}

export type ChallengeDayMaxAggregateOutputType = {
  id: string | null
  challengeId: string | null
  dayNumber: number | null
  date: Date | null
  description: string | null
  category: $Enums.ChallengeCategory | null
  createdAt: Date | null
}

export type ChallengeDayCountAggregateOutputType = {
  id: number
  challengeId: number
  dayNumber: number
  date: number
  description: number
  category: number
  createdAt: number
  _all: number
}


export type ChallengeDayAvgAggregateInputType = {
  dayNumber?: true
}

export type ChallengeDaySumAggregateInputType = {
  dayNumber?: true
}

export type ChallengeDayMinAggregateInputType = {
  id?: true
  challengeId?: true
  dayNumber?: true
  date?: true
  description?: true
  category?: true
  createdAt?: true
}

export type ChallengeDayMaxAggregateInputType = {
  id?: true
  challengeId?: true
  dayNumber?: true
  date?: true
  description?: true
  category?: true
  createdAt?: true
}

export type ChallengeDayCountAggregateInputType = {
  id?: true
  challengeId?: true
  dayNumber?: true
  date?: true
  description?: true
  category?: true
  createdAt?: true
  _all?: true
}

export type ChallengeDayAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ChallengeDay to aggregate.
   */
  where?: Prisma.ChallengeDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChallengeDays to fetch.
   */
  orderBy?: Prisma.ChallengeDayOrderByWithRelationInput | Prisma.ChallengeDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ChallengeDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChallengeDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChallengeDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ChallengeDays
  **/
  _count?: true | ChallengeDayCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ChallengeDayAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ChallengeDaySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ChallengeDayMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ChallengeDayMaxAggregateInputType
}

export type GetChallengeDayAggregateType<T extends ChallengeDayAggregateArgs> = {
      [P in keyof T & keyof AggregateChallengeDay]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateChallengeDay[P]>
    : Prisma.GetScalarType<T[P], AggregateChallengeDay[P]>
}




export type ChallengeDayGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChallengeDayWhereInput
  orderBy?: Prisma.ChallengeDayOrderByWithAggregationInput | Prisma.ChallengeDayOrderByWithAggregationInput[]
  by: Prisma.ChallengeDayScalarFieldEnum[] | Prisma.ChallengeDayScalarFieldEnum
  having?: Prisma.ChallengeDayScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ChallengeDayCountAggregateInputType | true
  _avg?: ChallengeDayAvgAggregateInputType
  _sum?: ChallengeDaySumAggregateInputType
  _min?: ChallengeDayMinAggregateInputType
  _max?: ChallengeDayMaxAggregateInputType
}

export type ChallengeDayGroupByOutputType = {
  id: string
  challengeId: string
  dayNumber: number
  date: Date
  description: string
  category: $Enums.ChallengeCategory
  createdAt: Date
  _count: ChallengeDayCountAggregateOutputType | null
  _avg: ChallengeDayAvgAggregateOutputType | null
  _sum: ChallengeDaySumAggregateOutputType | null
  _min: ChallengeDayMinAggregateOutputType | null
  _max: ChallengeDayMaxAggregateOutputType | null
}

export type GetChallengeDayGroupByPayload<T extends ChallengeDayGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ChallengeDayGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ChallengeDayGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ChallengeDayGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ChallengeDayGroupByOutputType[P]>
      }
    >
  >



export type ChallengeDayWhereInput = {
  AND?: Prisma.ChallengeDayWhereInput | Prisma.ChallengeDayWhereInput[]
  OR?: Prisma.ChallengeDayWhereInput[]
  NOT?: Prisma.ChallengeDayWhereInput | Prisma.ChallengeDayWhereInput[]
  id?: Prisma.StringFilter<"ChallengeDay"> | string
  challengeId?: Prisma.StringFilter<"ChallengeDay"> | string
  dayNumber?: Prisma.IntFilter<"ChallengeDay"> | number
  date?: Prisma.DateTimeFilter<"ChallengeDay"> | Date | string
  description?: Prisma.StringFilter<"ChallengeDay"> | string
  category?: Prisma.EnumChallengeCategoryFilter<"ChallengeDay"> | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeFilter<"ChallengeDay"> | Date | string
  challenge?: Prisma.XOR<Prisma.ChallengeScalarRelationFilter, Prisma.ChallengeWhereInput>
}

export type ChallengeDayOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  challengeId?: Prisma.SortOrder
  dayNumber?: Prisma.SortOrder
  date?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  challenge?: Prisma.ChallengeOrderByWithRelationInput
}

export type ChallengeDayWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  challengeId_dayNumber?: Prisma.ChallengeDayChallengeIdDayNumberCompoundUniqueInput
  challengeId_date?: Prisma.ChallengeDayChallengeIdDateCompoundUniqueInput
  AND?: Prisma.ChallengeDayWhereInput | Prisma.ChallengeDayWhereInput[]
  OR?: Prisma.ChallengeDayWhereInput[]
  NOT?: Prisma.ChallengeDayWhereInput | Prisma.ChallengeDayWhereInput[]
  challengeId?: Prisma.StringFilter<"ChallengeDay"> | string
  dayNumber?: Prisma.IntFilter<"ChallengeDay"> | number
  date?: Prisma.DateTimeFilter<"ChallengeDay"> | Date | string
  description?: Prisma.StringFilter<"ChallengeDay"> | string
  category?: Prisma.EnumChallengeCategoryFilter<"ChallengeDay"> | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeFilter<"ChallengeDay"> | Date | string
  challenge?: Prisma.XOR<Prisma.ChallengeScalarRelationFilter, Prisma.ChallengeWhereInput>
}, "id" | "challengeId_dayNumber" | "challengeId_date">

export type ChallengeDayOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  challengeId?: Prisma.SortOrder
  dayNumber?: Prisma.SortOrder
  date?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ChallengeDayCountOrderByAggregateInput
  _avg?: Prisma.ChallengeDayAvgOrderByAggregateInput
  _max?: Prisma.ChallengeDayMaxOrderByAggregateInput
  _min?: Prisma.ChallengeDayMinOrderByAggregateInput
  _sum?: Prisma.ChallengeDaySumOrderByAggregateInput
}

export type ChallengeDayScalarWhereWithAggregatesInput = {
  AND?: Prisma.ChallengeDayScalarWhereWithAggregatesInput | Prisma.ChallengeDayScalarWhereWithAggregatesInput[]
  OR?: Prisma.ChallengeDayScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ChallengeDayScalarWhereWithAggregatesInput | Prisma.ChallengeDayScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ChallengeDay"> | string
  challengeId?: Prisma.StringWithAggregatesFilter<"ChallengeDay"> | string
  dayNumber?: Prisma.IntWithAggregatesFilter<"ChallengeDay"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"ChallengeDay"> | Date | string
  description?: Prisma.StringWithAggregatesFilter<"ChallengeDay"> | string
  category?: Prisma.EnumChallengeCategoryWithAggregatesFilter<"ChallengeDay"> | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ChallengeDay"> | Date | string
}

export type ChallengeDayCreateInput = {
  id?: string
  dayNumber: number
  date: Date | string
  description: string
  category: $Enums.ChallengeCategory
  createdAt?: Date | string
  challenge: Prisma.ChallengeCreateNestedOneWithoutDaysInput
}

export type ChallengeDayUncheckedCreateInput = {
  id?: string
  challengeId: string
  dayNumber: number
  date: Date | string
  description: string
  category: $Enums.ChallengeCategory
  createdAt?: Date | string
}

export type ChallengeDayUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumChallengeCategoryFieldUpdateOperationsInput | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  challenge?: Prisma.ChallengeUpdateOneRequiredWithoutDaysNestedInput
}

export type ChallengeDayUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  challengeId?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumChallengeCategoryFieldUpdateOperationsInput | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChallengeDayCreateManyInput = {
  id?: string
  challengeId: string
  dayNumber: number
  date: Date | string
  description: string
  category: $Enums.ChallengeCategory
  createdAt?: Date | string
}

export type ChallengeDayUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumChallengeCategoryFieldUpdateOperationsInput | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChallengeDayUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  challengeId?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumChallengeCategoryFieldUpdateOperationsInput | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChallengeDayListRelationFilter = {
  every?: Prisma.ChallengeDayWhereInput
  some?: Prisma.ChallengeDayWhereInput
  none?: Prisma.ChallengeDayWhereInput
}

export type ChallengeDayOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ChallengeDayChallengeIdDayNumberCompoundUniqueInput = {
  challengeId: string
  dayNumber: number
}

export type ChallengeDayChallengeIdDateCompoundUniqueInput = {
  challengeId: string
  date: Date | string
}

export type ChallengeDayCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  challengeId?: Prisma.SortOrder
  dayNumber?: Prisma.SortOrder
  date?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ChallengeDayAvgOrderByAggregateInput = {
  dayNumber?: Prisma.SortOrder
}

export type ChallengeDayMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  challengeId?: Prisma.SortOrder
  dayNumber?: Prisma.SortOrder
  date?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ChallengeDayMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  challengeId?: Prisma.SortOrder
  dayNumber?: Prisma.SortOrder
  date?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ChallengeDaySumOrderByAggregateInput = {
  dayNumber?: Prisma.SortOrder
}

export type ChallengeDayCreateNestedManyWithoutChallengeInput = {
  create?: Prisma.XOR<Prisma.ChallengeDayCreateWithoutChallengeInput, Prisma.ChallengeDayUncheckedCreateWithoutChallengeInput> | Prisma.ChallengeDayCreateWithoutChallengeInput[] | Prisma.ChallengeDayUncheckedCreateWithoutChallengeInput[]
  connectOrCreate?: Prisma.ChallengeDayCreateOrConnectWithoutChallengeInput | Prisma.ChallengeDayCreateOrConnectWithoutChallengeInput[]
  createMany?: Prisma.ChallengeDayCreateManyChallengeInputEnvelope
  connect?: Prisma.ChallengeDayWhereUniqueInput | Prisma.ChallengeDayWhereUniqueInput[]
}

export type ChallengeDayUncheckedCreateNestedManyWithoutChallengeInput = {
  create?: Prisma.XOR<Prisma.ChallengeDayCreateWithoutChallengeInput, Prisma.ChallengeDayUncheckedCreateWithoutChallengeInput> | Prisma.ChallengeDayCreateWithoutChallengeInput[] | Prisma.ChallengeDayUncheckedCreateWithoutChallengeInput[]
  connectOrCreate?: Prisma.ChallengeDayCreateOrConnectWithoutChallengeInput | Prisma.ChallengeDayCreateOrConnectWithoutChallengeInput[]
  createMany?: Prisma.ChallengeDayCreateManyChallengeInputEnvelope
  connect?: Prisma.ChallengeDayWhereUniqueInput | Prisma.ChallengeDayWhereUniqueInput[]
}

export type ChallengeDayUpdateManyWithoutChallengeNestedInput = {
  create?: Prisma.XOR<Prisma.ChallengeDayCreateWithoutChallengeInput, Prisma.ChallengeDayUncheckedCreateWithoutChallengeInput> | Prisma.ChallengeDayCreateWithoutChallengeInput[] | Prisma.ChallengeDayUncheckedCreateWithoutChallengeInput[]
  connectOrCreate?: Prisma.ChallengeDayCreateOrConnectWithoutChallengeInput | Prisma.ChallengeDayCreateOrConnectWithoutChallengeInput[]
  upsert?: Prisma.ChallengeDayUpsertWithWhereUniqueWithoutChallengeInput | Prisma.ChallengeDayUpsertWithWhereUniqueWithoutChallengeInput[]
  createMany?: Prisma.ChallengeDayCreateManyChallengeInputEnvelope
  set?: Prisma.ChallengeDayWhereUniqueInput | Prisma.ChallengeDayWhereUniqueInput[]
  disconnect?: Prisma.ChallengeDayWhereUniqueInput | Prisma.ChallengeDayWhereUniqueInput[]
  delete?: Prisma.ChallengeDayWhereUniqueInput | Prisma.ChallengeDayWhereUniqueInput[]
  connect?: Prisma.ChallengeDayWhereUniqueInput | Prisma.ChallengeDayWhereUniqueInput[]
  update?: Prisma.ChallengeDayUpdateWithWhereUniqueWithoutChallengeInput | Prisma.ChallengeDayUpdateWithWhereUniqueWithoutChallengeInput[]
  updateMany?: Prisma.ChallengeDayUpdateManyWithWhereWithoutChallengeInput | Prisma.ChallengeDayUpdateManyWithWhereWithoutChallengeInput[]
  deleteMany?: Prisma.ChallengeDayScalarWhereInput | Prisma.ChallengeDayScalarWhereInput[]
}

export type ChallengeDayUncheckedUpdateManyWithoutChallengeNestedInput = {
  create?: Prisma.XOR<Prisma.ChallengeDayCreateWithoutChallengeInput, Prisma.ChallengeDayUncheckedCreateWithoutChallengeInput> | Prisma.ChallengeDayCreateWithoutChallengeInput[] | Prisma.ChallengeDayUncheckedCreateWithoutChallengeInput[]
  connectOrCreate?: Prisma.ChallengeDayCreateOrConnectWithoutChallengeInput | Prisma.ChallengeDayCreateOrConnectWithoutChallengeInput[]
  upsert?: Prisma.ChallengeDayUpsertWithWhereUniqueWithoutChallengeInput | Prisma.ChallengeDayUpsertWithWhereUniqueWithoutChallengeInput[]
  createMany?: Prisma.ChallengeDayCreateManyChallengeInputEnvelope
  set?: Prisma.ChallengeDayWhereUniqueInput | Prisma.ChallengeDayWhereUniqueInput[]
  disconnect?: Prisma.ChallengeDayWhereUniqueInput | Prisma.ChallengeDayWhereUniqueInput[]
  delete?: Prisma.ChallengeDayWhereUniqueInput | Prisma.ChallengeDayWhereUniqueInput[]
  connect?: Prisma.ChallengeDayWhereUniqueInput | Prisma.ChallengeDayWhereUniqueInput[]
  update?: Prisma.ChallengeDayUpdateWithWhereUniqueWithoutChallengeInput | Prisma.ChallengeDayUpdateWithWhereUniqueWithoutChallengeInput[]
  updateMany?: Prisma.ChallengeDayUpdateManyWithWhereWithoutChallengeInput | Prisma.ChallengeDayUpdateManyWithWhereWithoutChallengeInput[]
  deleteMany?: Prisma.ChallengeDayScalarWhereInput | Prisma.ChallengeDayScalarWhereInput[]
}

export type EnumChallengeCategoryFieldUpdateOperationsInput = {
  set?: $Enums.ChallengeCategory
}

export type ChallengeDayCreateWithoutChallengeInput = {
  id?: string
  dayNumber: number
  date: Date | string
  description: string
  category: $Enums.ChallengeCategory
  createdAt?: Date | string
}

export type ChallengeDayUncheckedCreateWithoutChallengeInput = {
  id?: string
  dayNumber: number
  date: Date | string
  description: string
  category: $Enums.ChallengeCategory
  createdAt?: Date | string
}

export type ChallengeDayCreateOrConnectWithoutChallengeInput = {
  where: Prisma.ChallengeDayWhereUniqueInput
  create: Prisma.XOR<Prisma.ChallengeDayCreateWithoutChallengeInput, Prisma.ChallengeDayUncheckedCreateWithoutChallengeInput>
}

export type ChallengeDayCreateManyChallengeInputEnvelope = {
  data: Prisma.ChallengeDayCreateManyChallengeInput | Prisma.ChallengeDayCreateManyChallengeInput[]
  skipDuplicates?: boolean
}

export type ChallengeDayUpsertWithWhereUniqueWithoutChallengeInput = {
  where: Prisma.ChallengeDayWhereUniqueInput
  update: Prisma.XOR<Prisma.ChallengeDayUpdateWithoutChallengeInput, Prisma.ChallengeDayUncheckedUpdateWithoutChallengeInput>
  create: Prisma.XOR<Prisma.ChallengeDayCreateWithoutChallengeInput, Prisma.ChallengeDayUncheckedCreateWithoutChallengeInput>
}

export type ChallengeDayUpdateWithWhereUniqueWithoutChallengeInput = {
  where: Prisma.ChallengeDayWhereUniqueInput
  data: Prisma.XOR<Prisma.ChallengeDayUpdateWithoutChallengeInput, Prisma.ChallengeDayUncheckedUpdateWithoutChallengeInput>
}

export type ChallengeDayUpdateManyWithWhereWithoutChallengeInput = {
  where: Prisma.ChallengeDayScalarWhereInput
  data: Prisma.XOR<Prisma.ChallengeDayUpdateManyMutationInput, Prisma.ChallengeDayUncheckedUpdateManyWithoutChallengeInput>
}

export type ChallengeDayScalarWhereInput = {
  AND?: Prisma.ChallengeDayScalarWhereInput | Prisma.ChallengeDayScalarWhereInput[]
  OR?: Prisma.ChallengeDayScalarWhereInput[]
  NOT?: Prisma.ChallengeDayScalarWhereInput | Prisma.ChallengeDayScalarWhereInput[]
  id?: Prisma.StringFilter<"ChallengeDay"> | string
  challengeId?: Prisma.StringFilter<"ChallengeDay"> | string
  dayNumber?: Prisma.IntFilter<"ChallengeDay"> | number
  date?: Prisma.DateTimeFilter<"ChallengeDay"> | Date | string
  description?: Prisma.StringFilter<"ChallengeDay"> | string
  category?: Prisma.EnumChallengeCategoryFilter<"ChallengeDay"> | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeFilter<"ChallengeDay"> | Date | string
}

export type ChallengeDayCreateManyChallengeInput = {
  id?: string
  dayNumber: number
  date: Date | string
  description: string
  category: $Enums.ChallengeCategory
  createdAt?: Date | string
}

export type ChallengeDayUpdateWithoutChallengeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumChallengeCategoryFieldUpdateOperationsInput | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChallengeDayUncheckedUpdateWithoutChallengeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumChallengeCategoryFieldUpdateOperationsInput | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChallengeDayUncheckedUpdateManyWithoutChallengeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumChallengeCategoryFieldUpdateOperationsInput | $Enums.ChallengeCategory
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ChallengeDaySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  challengeId?: boolean
  dayNumber?: boolean
  date?: boolean
  description?: boolean
  category?: boolean
  createdAt?: boolean
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["challengeDay"]>

export type ChallengeDaySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  challengeId?: boolean
  dayNumber?: boolean
  date?: boolean
  description?: boolean
  category?: boolean
  createdAt?: boolean
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["challengeDay"]>

export type ChallengeDaySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  challengeId?: boolean
  dayNumber?: boolean
  date?: boolean
  description?: boolean
  category?: boolean
  createdAt?: boolean
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["challengeDay"]>

export type ChallengeDaySelectScalar = {
  id?: boolean
  challengeId?: boolean
  dayNumber?: boolean
  date?: boolean
  description?: boolean
  category?: boolean
  createdAt?: boolean
}

export type ChallengeDayOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "challengeId" | "dayNumber" | "date" | "description" | "category" | "createdAt", ExtArgs["result"]["challengeDay"]>
export type ChallengeDayInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
}
export type ChallengeDayIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
}
export type ChallengeDayIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
}

export type $ChallengeDayPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ChallengeDay"
  objects: {
    challenge: Prisma.$ChallengePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    challengeId: string
    dayNumber: number
    date: Date
    description: string
    category: $Enums.ChallengeCategory
    createdAt: Date
  }, ExtArgs["result"]["challengeDay"]>
  composites: {}
}

export type ChallengeDayGetPayload<S extends boolean | null | undefined | ChallengeDayDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload, S>

export type ChallengeDayCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ChallengeDayFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ChallengeDayCountAggregateInputType | true
  }

export interface ChallengeDayDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ChallengeDay'], meta: { name: 'ChallengeDay' } }
  /**
   * Find zero or one ChallengeDay that matches the filter.
   * @param {ChallengeDayFindUniqueArgs} args - Arguments to find a ChallengeDay
   * @example
   * // Get one ChallengeDay
   * const challengeDay = await prisma.challengeDay.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ChallengeDayFindUniqueArgs>(args: Prisma.SelectSubset<T, ChallengeDayFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ChallengeDayClient<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ChallengeDay that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ChallengeDayFindUniqueOrThrowArgs} args - Arguments to find a ChallengeDay
   * @example
   * // Get one ChallengeDay
   * const challengeDay = await prisma.challengeDay.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ChallengeDayFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ChallengeDayFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChallengeDayClient<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ChallengeDay that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChallengeDayFindFirstArgs} args - Arguments to find a ChallengeDay
   * @example
   * // Get one ChallengeDay
   * const challengeDay = await prisma.challengeDay.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ChallengeDayFindFirstArgs>(args?: Prisma.SelectSubset<T, ChallengeDayFindFirstArgs<ExtArgs>>): Prisma.Prisma__ChallengeDayClient<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ChallengeDay that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChallengeDayFindFirstOrThrowArgs} args - Arguments to find a ChallengeDay
   * @example
   * // Get one ChallengeDay
   * const challengeDay = await prisma.challengeDay.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ChallengeDayFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ChallengeDayFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChallengeDayClient<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ChallengeDays that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChallengeDayFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ChallengeDays
   * const challengeDays = await prisma.challengeDay.findMany()
   * 
   * // Get first 10 ChallengeDays
   * const challengeDays = await prisma.challengeDay.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const challengeDayWithIdOnly = await prisma.challengeDay.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ChallengeDayFindManyArgs>(args?: Prisma.SelectSubset<T, ChallengeDayFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ChallengeDay.
   * @param {ChallengeDayCreateArgs} args - Arguments to create a ChallengeDay.
   * @example
   * // Create one ChallengeDay
   * const ChallengeDay = await prisma.challengeDay.create({
   *   data: {
   *     // ... data to create a ChallengeDay
   *   }
   * })
   * 
   */
  create<T extends ChallengeDayCreateArgs>(args: Prisma.SelectSubset<T, ChallengeDayCreateArgs<ExtArgs>>): Prisma.Prisma__ChallengeDayClient<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ChallengeDays.
   * @param {ChallengeDayCreateManyArgs} args - Arguments to create many ChallengeDays.
   * @example
   * // Create many ChallengeDays
   * const challengeDay = await prisma.challengeDay.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ChallengeDayCreateManyArgs>(args?: Prisma.SelectSubset<T, ChallengeDayCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ChallengeDays and returns the data saved in the database.
   * @param {ChallengeDayCreateManyAndReturnArgs} args - Arguments to create many ChallengeDays.
   * @example
   * // Create many ChallengeDays
   * const challengeDay = await prisma.challengeDay.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ChallengeDays and only return the `id`
   * const challengeDayWithIdOnly = await prisma.challengeDay.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ChallengeDayCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ChallengeDayCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ChallengeDay.
   * @param {ChallengeDayDeleteArgs} args - Arguments to delete one ChallengeDay.
   * @example
   * // Delete one ChallengeDay
   * const ChallengeDay = await prisma.challengeDay.delete({
   *   where: {
   *     // ... filter to delete one ChallengeDay
   *   }
   * })
   * 
   */
  delete<T extends ChallengeDayDeleteArgs>(args: Prisma.SelectSubset<T, ChallengeDayDeleteArgs<ExtArgs>>): Prisma.Prisma__ChallengeDayClient<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ChallengeDay.
   * @param {ChallengeDayUpdateArgs} args - Arguments to update one ChallengeDay.
   * @example
   * // Update one ChallengeDay
   * const challengeDay = await prisma.challengeDay.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ChallengeDayUpdateArgs>(args: Prisma.SelectSubset<T, ChallengeDayUpdateArgs<ExtArgs>>): Prisma.Prisma__ChallengeDayClient<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ChallengeDays.
   * @param {ChallengeDayDeleteManyArgs} args - Arguments to filter ChallengeDays to delete.
   * @example
   * // Delete a few ChallengeDays
   * const { count } = await prisma.challengeDay.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ChallengeDayDeleteManyArgs>(args?: Prisma.SelectSubset<T, ChallengeDayDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ChallengeDays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChallengeDayUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ChallengeDays
   * const challengeDay = await prisma.challengeDay.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ChallengeDayUpdateManyArgs>(args: Prisma.SelectSubset<T, ChallengeDayUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ChallengeDays and returns the data updated in the database.
   * @param {ChallengeDayUpdateManyAndReturnArgs} args - Arguments to update many ChallengeDays.
   * @example
   * // Update many ChallengeDays
   * const challengeDay = await prisma.challengeDay.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ChallengeDays and only return the `id`
   * const challengeDayWithIdOnly = await prisma.challengeDay.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ChallengeDayUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ChallengeDayUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ChallengeDay.
   * @param {ChallengeDayUpsertArgs} args - Arguments to update or create a ChallengeDay.
   * @example
   * // Update or create a ChallengeDay
   * const challengeDay = await prisma.challengeDay.upsert({
   *   create: {
   *     // ... data to create a ChallengeDay
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ChallengeDay we want to update
   *   }
   * })
   */
  upsert<T extends ChallengeDayUpsertArgs>(args: Prisma.SelectSubset<T, ChallengeDayUpsertArgs<ExtArgs>>): Prisma.Prisma__ChallengeDayClient<runtime.Types.Result.GetResult<Prisma.$ChallengeDayPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ChallengeDays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChallengeDayCountArgs} args - Arguments to filter ChallengeDays to count.
   * @example
   * // Count the number of ChallengeDays
   * const count = await prisma.challengeDay.count({
   *   where: {
   *     // ... the filter for the ChallengeDays we want to count
   *   }
   * })
  **/
  count<T extends ChallengeDayCountArgs>(
    args?: Prisma.Subset<T, ChallengeDayCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ChallengeDayCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ChallengeDay.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChallengeDayAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ChallengeDayAggregateArgs>(args: Prisma.Subset<T, ChallengeDayAggregateArgs>): Prisma.PrismaPromise<GetChallengeDayAggregateType<T>>

  /**
   * Group by ChallengeDay.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChallengeDayGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ChallengeDayGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ChallengeDayGroupByArgs['orderBy'] }
      : { orderBy?: ChallengeDayGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ChallengeDayGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetChallengeDayGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ChallengeDay model
 */
readonly fields: ChallengeDayFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ChallengeDay.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ChallengeDayClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  challenge<T extends Prisma.ChallengeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChallengeDefaultArgs<ExtArgs>>): Prisma.Prisma__ChallengeClient<runtime.Types.Result.GetResult<Prisma.$ChallengePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ChallengeDay model
 */
export interface ChallengeDayFieldRefs {
  readonly id: Prisma.FieldRef<"ChallengeDay", 'String'>
  readonly challengeId: Prisma.FieldRef<"ChallengeDay", 'String'>
  readonly dayNumber: Prisma.FieldRef<"ChallengeDay", 'Int'>
  readonly date: Prisma.FieldRef<"ChallengeDay", 'DateTime'>
  readonly description: Prisma.FieldRef<"ChallengeDay", 'String'>
  readonly category: Prisma.FieldRef<"ChallengeDay", 'ChallengeCategory'>
  readonly createdAt: Prisma.FieldRef<"ChallengeDay", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ChallengeDay findUnique
 */
export type ChallengeDayFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayInclude<ExtArgs> | null
  /**
   * Filter, which ChallengeDay to fetch.
   */
  where: Prisma.ChallengeDayWhereUniqueInput
}

/**
 * ChallengeDay findUniqueOrThrow
 */
export type ChallengeDayFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayInclude<ExtArgs> | null
  /**
   * Filter, which ChallengeDay to fetch.
   */
  where: Prisma.ChallengeDayWhereUniqueInput
}

/**
 * ChallengeDay findFirst
 */
export type ChallengeDayFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayInclude<ExtArgs> | null
  /**
   * Filter, which ChallengeDay to fetch.
   */
  where?: Prisma.ChallengeDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChallengeDays to fetch.
   */
  orderBy?: Prisma.ChallengeDayOrderByWithRelationInput | Prisma.ChallengeDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ChallengeDays.
   */
  cursor?: Prisma.ChallengeDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChallengeDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChallengeDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChallengeDays.
   */
  distinct?: Prisma.ChallengeDayScalarFieldEnum | Prisma.ChallengeDayScalarFieldEnum[]
}

/**
 * ChallengeDay findFirstOrThrow
 */
export type ChallengeDayFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayInclude<ExtArgs> | null
  /**
   * Filter, which ChallengeDay to fetch.
   */
  where?: Prisma.ChallengeDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChallengeDays to fetch.
   */
  orderBy?: Prisma.ChallengeDayOrderByWithRelationInput | Prisma.ChallengeDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ChallengeDays.
   */
  cursor?: Prisma.ChallengeDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChallengeDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChallengeDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChallengeDays.
   */
  distinct?: Prisma.ChallengeDayScalarFieldEnum | Prisma.ChallengeDayScalarFieldEnum[]
}

/**
 * ChallengeDay findMany
 */
export type ChallengeDayFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayInclude<ExtArgs> | null
  /**
   * Filter, which ChallengeDays to fetch.
   */
  where?: Prisma.ChallengeDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChallengeDays to fetch.
   */
  orderBy?: Prisma.ChallengeDayOrderByWithRelationInput | Prisma.ChallengeDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ChallengeDays.
   */
  cursor?: Prisma.ChallengeDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChallengeDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChallengeDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChallengeDays.
   */
  distinct?: Prisma.ChallengeDayScalarFieldEnum | Prisma.ChallengeDayScalarFieldEnum[]
}

/**
 * ChallengeDay create
 */
export type ChallengeDayCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayInclude<ExtArgs> | null
  /**
   * The data needed to create a ChallengeDay.
   */
  data: Prisma.XOR<Prisma.ChallengeDayCreateInput, Prisma.ChallengeDayUncheckedCreateInput>
}

/**
 * ChallengeDay createMany
 */
export type ChallengeDayCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ChallengeDays.
   */
  data: Prisma.ChallengeDayCreateManyInput | Prisma.ChallengeDayCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ChallengeDay createManyAndReturn
 */
export type ChallengeDayCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * The data used to create many ChallengeDays.
   */
  data: Prisma.ChallengeDayCreateManyInput | Prisma.ChallengeDayCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ChallengeDay update
 */
export type ChallengeDayUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayInclude<ExtArgs> | null
  /**
   * The data needed to update a ChallengeDay.
   */
  data: Prisma.XOR<Prisma.ChallengeDayUpdateInput, Prisma.ChallengeDayUncheckedUpdateInput>
  /**
   * Choose, which ChallengeDay to update.
   */
  where: Prisma.ChallengeDayWhereUniqueInput
}

/**
 * ChallengeDay updateMany
 */
export type ChallengeDayUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ChallengeDays.
   */
  data: Prisma.XOR<Prisma.ChallengeDayUpdateManyMutationInput, Prisma.ChallengeDayUncheckedUpdateManyInput>
  /**
   * Filter which ChallengeDays to update
   */
  where?: Prisma.ChallengeDayWhereInput
  /**
   * Limit how many ChallengeDays to update.
   */
  limit?: number
}

/**
 * ChallengeDay updateManyAndReturn
 */
export type ChallengeDayUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * The data used to update ChallengeDays.
   */
  data: Prisma.XOR<Prisma.ChallengeDayUpdateManyMutationInput, Prisma.ChallengeDayUncheckedUpdateManyInput>
  /**
   * Filter which ChallengeDays to update
   */
  where?: Prisma.ChallengeDayWhereInput
  /**
   * Limit how many ChallengeDays to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ChallengeDay upsert
 */
export type ChallengeDayUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayInclude<ExtArgs> | null
  /**
   * The filter to search for the ChallengeDay to update in case it exists.
   */
  where: Prisma.ChallengeDayWhereUniqueInput
  /**
   * In case the ChallengeDay found by the `where` argument doesn't exist, create a new ChallengeDay with this data.
   */
  create: Prisma.XOR<Prisma.ChallengeDayCreateInput, Prisma.ChallengeDayUncheckedCreateInput>
  /**
   * In case the ChallengeDay was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ChallengeDayUpdateInput, Prisma.ChallengeDayUncheckedUpdateInput>
}

/**
 * ChallengeDay delete
 */
export type ChallengeDayDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayInclude<ExtArgs> | null
  /**
   * Filter which ChallengeDay to delete.
   */
  where: Prisma.ChallengeDayWhereUniqueInput
}

/**
 * ChallengeDay deleteMany
 */
export type ChallengeDayDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ChallengeDays to delete
   */
  where?: Prisma.ChallengeDayWhereInput
  /**
   * Limit how many ChallengeDays to delete.
   */
  limit?: number
}

/**
 * ChallengeDay without action
 */
export type ChallengeDayDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeDay
   */
  select?: Prisma.ChallengeDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeDay
   */
  omit?: Prisma.ChallengeDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeDayInclude<ExtArgs> | null
}
