import { FormEvent, useEffect, useState } from 'react'
import { apiFetch, localDateInput } from './lib/api'

type Goal = { id: string; title: string; dueDate: string | null; progress: number; isActive: boolean; createdAt: string }
const rewards = ['Well done — you did it!', 'Goal complete. Take a moment to celebrate.', 'You kept your promise to yourself.']

export default function Goals() {
  const [goals, setGoals] = useState<Goal[]>([]); const [title, setTitle] = useState(''); const [dueDate, setDueDate] = useState(''); const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState('')
  const load = () => apiFetch('/api/goals').then(async r => { if (!r.ok) throw new Error(); setGoals((await r.json() as { goals: Goal[] }).goals) }).catch(() => setMessage('Unable to load goals.'))
  useEffect(() => { load() }, [])
  async function add(event: FormEvent) { event.preventDefault(); setMessage(''); const response = await apiFetch('/api/goals', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, dueDate: dueDate || null }) }); if (!response.ok) return setMessage('Unable to save this goal.'); setTitle(''); setDueDate(''); load() }
  async function save(goal: Goal, values: Partial<Goal>) { const progress = values.progress ?? goal.progress; const response = await apiFetch(`/api/goals/${goal.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); if (!response.ok) return setMessage('Unable to update this goal.'); if (goal.progress < 100 && progress === 100) setMessage(rewards[Math.floor(Math.random() * rewards.length)]); setEditing(null); load() }
  async function remove(goal: Goal) { if (!window.confirm(`Delete “${goal.title}”?`)) return; const response = await apiFetch(`/api/goals/${goal.id}`, { method: 'DELETE' }); if (!response.ok) return setMessage('Unable to delete this goal.'); setMessage('Goal deleted.'); load() }
  return <main className="dashboard-shell"><header className="masthead"><div><p className="eyebrow">TIME LENS</p><h1>Goals that matter</h1></div><p className="quiet">Start today, choose a finish date, and celebrate the follow-through.</p></header><form className="goal-form panel" onSubmit={add}><input value={title} onChange={e => setTitle(e.target.value)} placeholder="What do you want to finish?" aria-label="Goal title" required /><label>Finish by<input value={dueDate} onChange={e => setDueDate(e.target.value)} type="date" min={localDateInput()} aria-label="Goal deadline" /></label><button>Add goal</button></form>{message && <p className="notice">{message}</p>}<section className="goals-list">{goals.length ? goals.map(goal => { const isEditing = editing === goal.id; return <article className="panel goal-row" key={goal.id}><div className="goal-copy">{isEditing ? <><input defaultValue={goal.title} onBlur={e => void save(goal, { title: e.target.value })} aria-label="Edit goal title" autoFocus /><label>Finish by<input type="date" defaultValue={goal.dueDate ?? ''} min={goal.createdAt} onChange={e => void save(goal, { dueDate: e.target.value || null })} /></label></> : <><h2>{goal.title}</h2><p className="quiet">From {goal.createdAt} {goal.dueDate ? `to ${goal.dueDate}` : 'with no finish date'} · {goal.progress}% complete</p></>}</div><div className="goal-actions"><input type="range" min="0" max="100" value={goal.progress} onChange={e => void save(goal, { progress: Number(e.target.value) })} aria-label={`${goal.title} progress`} /><button type="button" onClick={() => setEditing(isEditing ? null : goal.id)}>{isEditing ? 'Done' : 'Edit'}</button><button type="button" className="danger-button" onClick={() => void remove(goal)}>Delete</button></div></article> }) : <p className="quiet">No goals yet. Add one that matters this week.</p>}</section></main>
}
