import { FormEvent, useEffect, useState } from 'react'
type Goal = { id: string; title: string; dueDate: string | null; progress: number; isActive: boolean }
export default function Goals() {
  const [goals, setGoals] = useState<Goal[]>([]); const [title, setTitle] = useState(''); const [dueDate, setDueDate] = useState(''); const [message, setMessage] = useState('')
  const load = () => fetch('/api/goals').then(async r => { if (!r.ok) throw new Error(); setGoals((await r.json() as { goals: Goal[] }).goals) }).catch(() => setMessage('Unable to load goals.'))
  useEffect(() => { load() }, [])
  async function add(event: FormEvent) { event.preventDefault(); setMessage(''); const response = await fetch('/api/goals', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, dueDate: dueDate || null }) }); if (!response.ok) { setMessage('Unable to save this goal.'); return }; setTitle(''); setDueDate(''); load() }
  async function update(goal: Goal, progress: number) { const response = await fetch(`/api/goals/${goal.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ progress }) }); if (!response.ok) { setMessage('Unable to update this goal.'); return }; load() }
  return <main className="dashboard-shell"><header className="masthead"><div><p className="eyebrow">TIME LENS</p><h1>Goals and planning</h1></div><p className="quiet">Keep the goal list small. Plan individual focus hours in the Daily Log.</p></header><form className="goal-form panel" onSubmit={add}><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Add a goal" aria-label="Goal title" required /><input value={dueDate} onChange={e => setDueDate(e.target.value)} type="date" aria-label="Optional goal deadline" /><button>Add goal</button></form>{message && <p className="notice">{message}</p>}<section className="goals-list">{goals.length ? goals.map(goal => <article className="panel goal-row" key={goal.id}><div><h2>{goal.title}</h2><p className="quiet">{goal.dueDate ? `Deadline: ${goal.dueDate}` : 'No deadline'} · {goal.progress}% complete</p></div><input type="range" min="0" max="100" value={goal.progress} onChange={e => void update(goal, Number(e.target.value))} aria-label={`${goal.title} progress`} /></article>) : <p className="quiet">No goals yet. Add one that matters this week.</p>}</section></main>
}
